# -*- coding: utf-8 -*-
"""Food Model Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rn3TdnRttIVW1TFFpPpvdrGcJI5O8aOi
"""

!pip install rfdetr

import cv2

def draw_detections(image, detections, output_path):
    bbox = detections.xyxy
    confidence = detections.confidence
    class_ids = detections.class_id

    for i in range(len(bbox)):
        x1, y1, x2, y2 = bbox[i]
        conf = confidence[i]
        cls_id = int(class_ids[i])

        cv2.rectangle(image, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 8)

        label = f'Class {cls_id}: {conf:.2f}'
        cv2.putText(image, label, (int(x1), int(y1) - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    cv2.imwrite(output_path, image)

import cv2
from rfdetr import RFDETRBase

model = RFDETRBase(pretrain_weights="/content/checkpoint_best_ema.pth")

images_paths = [
    "/content/Turk-Yemek-Kulturu.jpeg",
    "/content/images.jpg",
    "/content/Variety-fruits-vegetables.webp"
]

for i, path in enumerate(images_paths):
    image = cv2.imread(path)

    detections = model.predict(image)
    print(detections)
    print(detections.xyxy)
    print(detections.confidence)
    print(detections.class_id)

    draw_detections(image, detections, f"output{i}.jpg")

