import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0a1812',
        padding: 20,
        paddingTop: 60,
    },
    backButton: {
        marginBottom: 20,
        alignSelf: 'flex-start',
        padding: 10,
    },
    profileHeader: {
        alignItems: 'center',
        marginBottom: 30,
        backgroundColor: '#14281d',
        padding: 20,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 8,
    },
    avatarContainer: {
        marginBottom: 15,
        borderWidth: 2,
        borderColor: '#47dd7caf',
        borderRadius: 50,
        padding: 2,
    },
    avatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#2a3d33',
    },
    avatarPlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#2a3d33',
        justifyContent: 'center',
        alignItems: 'center',
    },
    userName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#f7e5c5',
        marginBottom: 5,
    },
    userEmail: {
        fontSize: 14,
        color: '#8e8e8e',
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 30,
    },
    statCard: {
        alignItems: 'center',
        backgroundColor: '#14281d',
        padding: 15,
        borderRadius: 15,
        flex: 1,
        marginHorizontal: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 5,
    },
    statValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#ffffff',
        marginBottom: 5,
    },
    statLabel: {
        fontSize: 14,
        color: '#8e8e8e',
    },
    menuItems: {
        flex: 1,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 10,
        backgroundColor: '#14281d',
        borderRadius: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 5,
    },
    menuItemText: {
        fontSize: 16,
        color: '#f7e5c5',
        marginLeft: 15,
        flex: 1,
    },
    logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#2a1a1a',
        padding: 16,
        borderRadius: 15,
        marginTop: 20,
        borderWidth: 1,
        borderColor: '#e57373',
    },
    logoutText: {
        color: '#e57373',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 10,
    },
    deleteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#2a1a1a',
        padding: 16,
        borderRadius: 15,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#e57373',
    },
    deleteText: {
        color: '#e57373',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 10,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
    },
    modalContent: {
        backgroundColor: '#14281d',
        padding: 30,
        borderRadius: 20,
        width: '80%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 8,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#f7e5c5',
        marginBottom: 20,
        textAlign: 'center',
    },
    modalMessage: {
        fontSize: 16,
        color: '#8e8e8e',
        marginBottom: 30,
        textAlign: 'center',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    modalButton: {
        flex: 1,
        padding: 15,
        borderRadius: 10,
        marginHorizontal: 5,
        alignItems: 'center',
    },
    modalButtonCancel: {
        backgroundColor: '#2a3d33',
    },
    modalButtonDelete: {
        backgroundColor: '#e57373',
    },
    modalButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '600',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#0a1812',
    },
    listModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.75)',
        justifyContent: 'flex-end',
    },
    listModalSheet: {
        backgroundColor: '#14281d',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingBottom: 30,
        maxHeight: '70%',
    },
    listModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 18,
        borderBottomWidth: 1,
        borderBottomColor: '#2a3d33',
    },
    listModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#f7e5c5',
    },
    userListItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 18,
    },
    userListAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        marginRight: 12,
        backgroundColor: '#2a3d33',
    },
    userListName: {
        fontSize: 15,
        color: '#f7e5c5',
        fontWeight: '500',
    },
    emptyListText: {
        textAlign: 'center',
        color: '#8e8e8e',
        marginTop: 24,
        fontSize: 14,
    },
});

export default styles;